services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: madabon
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
