name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json

      - run: npm ci

      - run: npm run build:unpack

      - run: Compress-Archive -Path dist/win-unpacked/* -Destination madabon-${{ inputs.version }}.zip

      - run: gh release create v${{ inputs.version }} --generate-notes madabon-${{ inputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
